version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./api:/api
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./api:/api
        networks:
            - code-network
    app:
        build:
            context: ./app/
        command: npm start
        volumes:
            - ./app/:/usr/app
            - /usr/app/node_modules
        ports:
            - "3000:3000"
networks:
    code-network:
        driver: bridge